OYG_MOD_POLICY=1

# policy.sh — enforce LG consent + webOSbrew update-blocker + telnet-disable policy.
#
# THREE JOBS, all applied at every boot because the on-device state
# changes on its own.
#
# ---------------------------------------------------------------------
# Job A — set webOSbrew's update-blocker flag.
# ---------------------------------------------------------------------
# We `touch` /var/luna/preferences/webosbrew_block_updates. webOSbrew's
# own /var/lib/webosbrew/startup.sh checks for this file at line ~62
# and, if present, bind-mounts a copy of /etc/hosts that has
#     snu.lge.com su-dev.lge.com su.lge.com su-ssl.lge.com
# appended (both IPv4 127.0.0.1 and IPv6 ::1). That bind runs BEFORE
# the run-parts /var/lib/webosbrew/init.d at line ~136, so our own
# /etc/hosts bind-mount (applied from our init.d hook) stacks on top
# and wins. This flag is therefore a FALLBACK for our own hosts-file
# mitigation, not a replacement. Our own network blocklist already
# contains those update servers, so on this device both layers hold
# the line. If our init.d hook ever fails to run, webOSbrew's own
# mechanism will still silently sinkhole the four update servers.
#
# ---------------------------------------------------------------------
# Job A2 — keep telnetd off.
# ---------------------------------------------------------------------
# We `touch` /var/luna/preferences/webosbrew_telnet_disabled. The
# webOSbrew startup.sh gates the `telnetd -l /bin/sh` launch on the
# ABSENCE of this file — present means "do not start telnetd". The
# default launch is `telnetd -l /bin/sh`, which is an unauthenticated
# root shell on the LAN: no password prompt, no banner, no log;
# anyone on the same network who can reach the TV gets a root shell
# as soon as the daemon is up. SSH is the operator's path in, so we
# deliberately do not touch /var/luna/preferences/webosbrew_sshd_enabled.
#
# ---------------------------------------------------------------------
# Job B — force-decline LG consents at the source.
# ---------------------------------------------------------------------
# /var/luna/preferences/eula is a JSON file (~5 KB, 25 _id entries) of
# the form:
#   {"eulaInfo":{"eulaList":[
#       {"updated":false,"fileName":"S_SVC_20141117001.html",
#        "version":"20141117001","_id":"8275",
#        "fileLocation":"/usr/palm/license/","id":"S_SVC",
#        "accepted":false}, ...]}}
#
# On this device six are "accepted":true right now: S_DPA, S_SVC, S_VNG,
# S_ADG, S_TAG, S_MKT. Note S_VNG is the Viewing Information Gathering
# consent — i.e. the ACR consent — so ACR is permitted when S_VNG is
# accepted. Earlier in this investigation all six were "false"; the
# state changes on its own (the system silently re-accepts them when a
# related component updates, when an account is re-bound, etc.) and
# must therefore be re-enforced at every boot.
#
# We:
#   1. back the file up ONCE to $OYG_BACKUP/eula.orig (never overwritten
#      so a later flip can't quietly corrupt the audit trail);
#   2. rewrite every "accepted":true to "accepted":false using sed.
#      sed is sufficient here: the file is generated by the vendor and
#      has a fixed shape, "id" is always immediately followed by
#      "accepted", and the literal pattern "accepted":true is
#      unambiguous in this file. We do NOT have python on the device.
#      We write to a temp file then mv — never edit in place.
#
# ALLOW-LIST:
#   OYG_TOS_IDS="S_VNG S_TAG"
#   When set, only entries whose "id" is in that list are declined.
#   The implementation per-id sed pattern is
#     s/"id":"S_VNG","accepted":true/"id":"S_VNG","accepted":false/
#   which is safe because "id" immediately precedes "accepted" in
#   every entry (verified). When OYG_TOS_IDS is NOT set, EVERY
#   "accepted":true becomes "accepted":false — the default, stronger
#   behaviour.
#
# ---------------------------------------------------------------------
# WARNINGS
# ---------------------------------------------------------------------
# Some of these consents gate real features. Declining S_SVC or S_DPA
# may disable LG service / smart-home functionality. This is
# INTENTIONAL: the owner has root, has investigated, and prefers
# "no LG cloud" over "all LG features". Decline at your own risk.
#
# Even with S_VNG (the ACR / viewing-information consent) declined,
# the ACR *engine* itself is installed and the ACR process is the
# `services` module's responsibility; our mic/capture neutralisation
# (the `mic` + `voice` modules) is what actually stops audio reaching
# it, and the `network` module's hosts-file bind stops its endpoints.
# Force-declining S_VNG removes the *legal cover* the vendor relies
# on; it does not on its own neutralise the engine. The combination
# is the point.
#
# ---------------------------------------------------------------------
# STATE KEYS
# ---------------------------------------------------------------------
#   policy.applied            "1" if harden completed cleanly
#   policy.flagfile           "/var/luna/preferences/webosbrew_block_updates"
#   policy.telnetflag         "/var/luna/preferences/webosbrew_telnet_disabled"
#   policy.eula.path          "/var/luna/preferences/eula"
#   policy.eula.backup        "$OYG_BACKUP/eula.orig"
#   policy.eula.flipped       count of entries flipped on the LAST run
#   policy.eula.allow         empty = decline all; otherwise space-list of ids
#   policy.eula.last.before   count of "accepted":true BEFORE last rewrite

POLICY_FLAG=${POLICY_FLAG:-/var/luna/preferences/webosbrew_block_updates}
POLICY_TELNET_FLAG=${POLICY_TELNET_FLAG:-/var/luna/preferences/webosbrew_telnet_disabled}
POLICY_EULA=${POLICY_EULA:-/var/luna/preferences/eula}
POLICY_EULA_BACKUP=${POLICY_EULA_BACKUP:-"$OYG_BACKUP/eula.orig"}

# _policy_eula_count_accepted <file>
#   Print the number of "accepted":true occurrences in <file>.
#   grep -c counts matching LINES, but the pattern may match more
#   than once per line on a minified file (it doesn't here — the
#   entries are on a single line each, so one match per entry).
#   We use grep -o + wc -l to count OCCURRENCES regardless of layout,
#   which is correct for either the pretty-printed or minified shape.
_policy_eula_count_accepted() {
    f=$1
    [ -r "$f" ] || { printf '0\n'; return 0; }
    if have grep; then
        grep -o '"accepted":true' "$f" 2>/dev/null | wc -l | tr -d ' '
    else
        # grep is mandatory on the device but degrade gracefully
        sed 's/"accepted":true/X/g' "$f" 2>/dev/null \
            | tr -cd 'X' | wc -c | tr -d ' '
    fi
}

# _policy_eula_collect_ids <file>
#   Print the list of "id":"..." values currently showing
#   "accepted":true, one per line. Used to name the offenders in
#   status output when the file isn't fully declined.
#   Implementation: awk walks the file, finding each "id":"..." and
#   then scoping the "accepted" check to the SAME entry (everything
#   up to the next opening brace `{` of the next object, or to the
#   end of the line / record). We do NOT scan forward to end-of-line
#   because the file may be minified and have multiple entries per
#   line — that earlier variant reported every id on the same line
#   as the first accepted:true match.
_policy_eula_collect_ids() {
    f=$1
    [ -r "$f" ] || return 0
    awk '
        {
            n = index($0, "\"id\":\"");
            while (n > 0) {
                rest = substr($0, n + length("\"id\":\""));
                endq = index(rest, "\"");
                if (endq == 0) break;
                id = substr(rest, 1, endq - 1);
                # Scope to the current entry: from the id to the next
                # "{" (start of next object) or end of record.
                tail = substr($0, n);
                end_entry = index(tail, "{");
                if (end_entry > 0) {
                    entry = substr(tail, 1, end_entry - 1);
                } else {
                    entry = tail;
                }
                if (index(entry, "\"accepted\":true") > 0) {
                    print id;
                }
                # Advance past this id; keep going.
                $0 = substr(rest, endq + 1);
                n = index($0, "\"id\":\"");
            }
        }
    ' "$f" 2>/dev/null
}

mod_policy_harden() {
    require_root
    ensure_dirs

    # -----------------------------------------------------------------
    # Job A — touch the webOSbrew update-blocker flag (idempotent).
    # -----------------------------------------------------------------
    flagdir=${POLICY_FLAG%/*}
    if [ ! -d "$flagdir" ]; then
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: mkdir -p %s\n' "$flagdir"
        elif ! mkdir -p "$flagdir" 2>/dev/null; then
            warn "policy: cannot create $flagdir — flag step skipped (Job B still runs)"
        fi
    fi

    if [ "$OYG_DRY_RUN" = "1" ]; then
        printf 'DRY-RUN: touch %s\n' "$POLICY_FLAG"
        ok "policy: webOSbrew update-blocker flag would be present at $POLICY_FLAG"
    else
        if run touch "$POLICY_FLAG" 2>/dev/null; then
            ok "policy: webOSbrew update-blocker flag present at $POLICY_FLAG"
        else
            warn "policy: touch $POLICY_FLAG failed (Job A2 + Job B still run)"
        fi
    fi
    state_put "policy.flagfile" "$POLICY_FLAG"

    # -----------------------------------------------------------------
    # Job A2 — touch the webOSbrew telnet-disable flag (idempotent).
    # -----------------------------------------------------------------
    # webOSbrew's startup.sh launches `telnetd -l /bin/sh` only when
    # this file is ABSENT. Keeping it present suppresses the launch
    # entirely. `telnetd -l /bin/sh` is an unauthenticated root shell
    # on the LAN — the operator's management path is SSH, so we want
    # telnetd off and never want it to come back on a reboot.
    tflagdir=${POLICY_TELNET_FLAG%/*}
    if [ ! -d "$tflagdir" ]; then
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: mkdir -p %s\n' "$tflagdir"
        elif ! mkdir -p "$tflagdir" 2>/dev/null; then
            warn "policy: cannot create $tflagdir — telnet-disable step skipped (Job B still runs)"
        fi
    fi

    if [ "$OYG_DRY_RUN" = "1" ]; then
        printf 'DRY-RUN: touch %s\n' "$POLICY_TELNET_FLAG"
        ok "policy: webOSbrew telnet-disable flag would be present at $POLICY_TELNET_FLAG"
    else
        if run touch "$POLICY_TELNET_FLAG" 2>/dev/null; then
            ok "policy: webOSbrew telnet-disable flag present at $POLICY_TELNET_FLAG"
        else
            warn "policy: touch $POLICY_TELNET_FLAG failed (Job B still runs)"
        fi
    fi
    state_put "policy.telnetflag" "$POLICY_TELNET_FLAG"

    # -----------------------------------------------------------------
    # Job B — force-decline LG consents.
    # -----------------------------------------------------------------
    if [ ! -e "$POLICY_EULA" ]; then
        warn "policy: $POLICY_EULA does not exist — Job B skipped"
        state_put "policy.eula.path" "$POLICY_EULA"
        state_put "policy.applied" "1"
        return 0
    fi
    state_put "policy.eula.path" "$POLICY_EULA"

    # 1. Back up once. Never overwrite the original.
    if [ ! -e "$POLICY_EULA_BACKUP" ]; then
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: cp -p %s %s\n' "$POLICY_EULA" "$POLICY_EULA_BACKUP"
        else
            if run cp -p "$POLICY_EULA" "$POLICY_EULA_BACKUP" 2>/dev/null; then
                ok "policy: backed up $POLICY_EULA to $POLICY_EULA_BACKUP"
            else
                err "policy: could not back up $POLICY_EULA — refusing to rewrite"
                return 1
            fi
        fi
    else
        ok "policy: backup already present at $POLICY_EULA_BACKUP (preserved)"
    fi
    state_put "policy.eula.backup" "$POLICY_EULA_BACKUP"

    # 2. Record BEFORE state.
    before=$(_policy_eula_count_accepted "$POLICY_EULA")
    state_put "policy.eula.last.before" "$before"

    # 3. Rewrite. We use sed; we write to a temp file and mv.
    #    The pattern "accepted":true → "accepted":false is unambiguous
    #    in this file because every entry's "accepted" is a literal
    #    JSON boolean, not a nested object. Verify before/after on
    #    the dry-run path so the operator sees the planned effect.
    tmp=$(mktemp 2>/dev/null) || {
        err "policy: mktemp failed — cannot write $POLICY_EULA"
        return 1
    }

    if [ -n "${OYG_TOS_IDS:-}" ]; then
        # Allow-list: decline ONLY the named ids.
        allow=$OYG_TOS_IDS
        state_put "policy.eula.allow" "$allow"
        ok "policy: allow-list active — declining only: $allow"
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: would rewrite per-id sed for: %s\n' "$allow"
        fi
        sed_cmd=""
        for id in $allow; do
            [ -z "$id" ] && continue
            # Per-id pattern is safe because "id" immediately precedes
            # "accepted" in every entry on this device.
            sed_cmd="$sed_cmd -e s/\"id\":\"$id\",\"accepted\":true/\"id\":\"$id\",\"accepted\":false/g"
        done
        # shellcheck disable=SC2086
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: sed%s %s > %s ; mv %s %s\n' \
                "$sed_cmd" "$POLICY_EULA" "$tmp" "$tmp" "$POLICY_EULA"
        else
            # shellcheck disable=SC2086
            if sed $sed_cmd "$POLICY_EULA" >"$tmp" 2>/dev/null \
                && mv "$tmp" "$POLICY_EULA" 2>/dev/null; then
                : # ok handled below
            else
                rm -f "$tmp" 2>/dev/null
                err "policy: sed rewrite failed for allow-list"
                return 1
            fi
        fi
    else
        # Default: decline ALL.
        state_put "policy.eula.allow" ""
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: sed -e s/"accepted":true/"accepted":false/g %s > %s ; mv %s %s\n' \
                "$POLICY_EULA" "$tmp" "$tmp" "$POLICY_EULA"
        else
            if sed -e 's/"accepted":true/"accepted":false/g' "$POLICY_EULA" >"$tmp" 2>/dev/null \
                && mv "$tmp" "$POLICY_EULA" 2>/dev/null; then
                : # ok handled below
            else
                rm -f "$tmp" 2>/dev/null
                err "policy: sed rewrite failed"
                return 1
            fi
        fi
    fi

    # 4. Verify AFTER state and JSON sanity.
    if [ "$OYG_DRY_RUN" = "1" ]; then
        # In dry-run we DO NOT mutate the file, so the AFTER count
        # would equal the BEFORE count. Report the planned effect
        # instead and skip the on-disk sanity check.
        if [ -n "${OYG_TOS_IDS:-}" ]; then
            n=$(printf '%s\n' "$OYG_TOS_IDS" | wc -w | tr -d ' ')
            ok "policy: would decline $n allow-listed entr(y/ies) (before=$before)"
        else
            ok "policy: would decline $before accepted entr(y/ies) (all)"
        fi
        state_put "policy.eula.flipped" "$before"
        state_put "policy.applied" "1"
        return 0
    fi

    after=$(_policy_eula_count_accepted "$POLICY_EULA")
    flipped=$((before - after))
    if [ "$flipped" -lt 0 ]; then
        flipped=0
    fi
    state_put "policy.eula.flipped" "$flipped"

    # JSON sanity: the file must still parse as JSON object start/end
    # and the "accepted" key must still appear the expected number of
    # times (we did not lose entries). We do a quick structural check
    # because there is no python here. We use awk to extract the first
    # and last non-whitespace bytes (head -c 1 is portable enough on
    # BusyBox; BSD tail -c 1 has line-buffering quirks we want to
    # avoid).
    first=$(awk 'NR==1 { sub(/^[[:space:]]+/, ""); printf "%s", substr($0, 1, 1); exit }' "$POLICY_EULA" 2>/dev/null)
    last=$(awk 'END { line = $0; sub(/[[:space:]]+$/, "", line); printf "%s", substr(line, length(line), 1) }' "$POLICY_EULA" 2>/dev/null)
    if [ "$first" != "{" ] || [ "$last" != "}" ]; then
        warn "policy: $POLICY_EULA lost its outer { } after rewrite — JSON may be malformed"
        warn "policy: restoring from backup $POLICY_EULA_BACKUP"
        if cp -p "$POLICY_EULA_BACKUP" "$POLICY_EULA" 2>/dev/null; then
            err 'policy: rollback succeeded; rerun `oyg harden --only policy` to retry'
            return 1
        fi
        err "policy: rollback FAILED — restore $POLICY_EULA manually from $POLICY_EULA_BACKUP"
        return 1
    fi

    ok "policy: rewrote $POLICY_EULA — flipped $flipped entr(y/ies) (before=$before after=$after)"

    state_put "policy.applied" "1"
    return 0
}

mod_policy_restore() {
    require_root

    rc=0

    # Job A — remove the webOSbrew update-blocker flag.
    if [ -e "$POLICY_FLAG" ]; then
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: rm -f %s\n' "$POLICY_FLAG"
        elif run rm -f "$POLICY_FLAG" 2>/dev/null; then
            ok "policy: removed webOSbrew update-blocker flag at $POLICY_FLAG"
        else
            warn "policy: could not remove $POLICY_FLAG — manual cleanup required"
            rc=1
        fi
    else
        ok "policy: webOSbrew update-blocker flag already absent"
    fi

    # Job A2 — remove the webOSbrew telnet-disable flag. WARNING:
    # removing this flag re-enables `telnetd -l /bin/sh` on the next
    # boot — an unauthenticated root shell on the LAN. We do not
    # silently drop it on `restore`; the operator must opt in by
    # running `oyg restore --only policy` and confirming. The
    # module still removes it when asked (restore is an explicit
    # undo of harden), and the WARN line above is the audit trail.
    if [ -e "$POLICY_TELNET_FLAG" ]; then
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: rm -f %s\n' "$POLICY_TELNET_FLAG"
        elif run rm -f "$POLICY_TELNET_FLAG" 2>/dev/null; then
            warn "policy: removed webOSbrew telnet-disable flag at $POLICY_TELNET_FLAG — telnetd may launch on next boot"
        else
            warn "policy: could not remove $POLICY_TELNET_FLAG — manual cleanup required"
            rc=1
        fi
    else
        ok "policy: webOSbrew telnet-disable flag already absent"
    fi

    # Job B — restore the EULA file from backup.
    if [ ! -e "$POLICY_EULA_BACKUP" ]; then
        warn "policy: no backup at $POLICY_EULA_BACKUP — cannot restore EULA"
        rc=1
    elif [ ! -e "$POLICY_EULA" ]; then
        warn "policy: $POLICY_EULA missing; nothing to restore"
    else
        if [ "$OYG_DRY_RUN" = "1" ]; then
            printf 'DRY-RUN: cp -p %s %s\n' "$POLICY_EULA_BACKUP" "$POLICY_EULA"
        elif run cp -p "$POLICY_EULA_BACKUP" "$POLICY_EULA" 2>/dev/null; then
            ok "policy: restored $POLICY_EULA from $POLICY_EULA_BACKUP"
        else
            warn "policy: cp $POLICY_EULA_BACKUP $POLICY_EULA failed"
            rc=1
        fi
    fi

    state_drop "policy.applied"
    state_drop "policy.flagfile"
    state_drop "policy.telnetflag"
    state_drop "policy.eula.path"
    state_drop "policy.eula.backup"
    state_drop "policy.eula.flipped"
    state_drop "policy.eula.allow"
    state_drop "policy.eula.last.before"

    return $rc
}

mod_policy_status() {
    # Job A: update-blocker flag check.
    if [ -e "$POLICY_FLAG" ]; then
        print_status OK "policy: webOSbrew update-blocker flag present at $POLICY_FLAG"
    else
        print_status FAIL "policy: webOSbrew update-blocker flag MISSING at $POLICY_FLAG"
    fi

    # Job A2: telnet-disable flag check. We report OK / FAIL on the
    # flag's own presence — its absence means webOSbrew's startup.sh
    # will launch `telnetd -l /bin/sh` on the next boot.
    if [ -e "$POLICY_TELNET_FLAG" ]; then
        print_status OK "policy: webOSbrew telnet-disable flag present at $POLICY_TELNET_FLAG"
    else
        print_status FAIL "policy: webOSbrew telnet-disable flag MISSING at $POLICY_TELNET_FLAG — telnetd may launch on next boot"
    fi

    # Job B: EULA check.
    if [ ! -e "$POLICY_EULA" ]; then
        print_status N/A "policy: $POLICY_EULA does not exist on this device"
        return
    fi

    applied=$(state_get "policy.applied")
    if [ "$applied" != "1" ]; then
        # First-time / pre-harden: just report what's there.
        cur=$(_policy_eula_count_accepted "$POLICY_EULA")
        if [ "$cur" = "0" ]; then
            print_status N/A "policy: $POLICY_EULA has zero accepted entries (not yet hardened)"
        else
            # Show offenders so the operator knows what would be declined.
            offenders=$(_policy_eula_collect_ids "$POLICY_EULA" | tr '\n' ',' | sed 's/,$//')
            print_status FAIL "policy: $POLICY_EULA has $cur accepted entr(y/ies): $offenders — not yet hardened"
        fi
        return
    fi

    cur=$(_policy_eula_count_accepted "$POLICY_EULA")
    allow=$(state_get "policy.eula.allow")
    flipped=$(state_get "policy.eula.flipped")
    before=$(state_get "policy.eula.last.before")

    if [ -n "$allow" ]; then
        # Allow-list mode: check that each allow-listed id is false.
        bad=""
        for id in $allow; do
            [ -z "$id" ] && continue
            if grep -q "\"id\":\"$id\",\"accepted\":true" "$POLICY_EULA" 2>/dev/null; then
                bad="$bad $id"
            fi
        done
        bad=$(trim "$bad")
        if [ -z "$bad" ]; then
            print_status OK "policy: allow-list $allow all declined (last flipped=$flipped before=$before current=$cur)"
        else
            print_status FAIL "policy: allow-list entries still accepted:$bad (current=$cur)"
        fi
    else
        # Default: every entry must be false.
        if [ "$cur" = "0" ]; then
            print_status OK "policy: zero accepted entries (last flipped=$flipped before=$before)"
        else
            offenders=$(_policy_eula_collect_ids "$POLICY_EULA" | tr '\n' ',' | sed 's/,$//')
            print_status FAIL "policy: $cur accepted entr(y/ies): $offenders"
        fi
    fi
}
