#!/bin/sh
# install.sh — install own-your-glass onto a rooted LG webOS TV.
#
# Layout on device:
#   /var/lib/own-your-glass/         tool root (state, backups, log, watchers)
#   /var/lib/webosbrew/init.d/oyg    boot hook (executed by run-parts)
#
# Idempotent: re-running re-installs files but does not re-apply hardening.
# Use `oyg harden` after install to actually harden.

set -u

OYG_SRC=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
OYG_DST=${OYG_DST:-/var/lib/own-your-glass}
INITD=${INITD:-/var/lib/webosbrew/init.d}
INIT_HOOK="$INITD/oyg"

log()  { printf '[install] %s\n' "$*"; }
warn() { printf '[install] WARN %s\n' "$*" >&2; }
err()  { printf '[install] ERR  %s\n' "$*" >&2; }
have() { command -v "$1" >/dev/null 2>&1; }

require_root() {
    if [ "$(id -u 2>/dev/null)" != "0" ]; then
        err "must be run as root on the device (or under sudo)"
        exit 1
    fi
}

require_dst_writable() {
    if ! mkdir -p "$OYG_DST" 2>/dev/null; then
        err "cannot create $OYG_DST (is /var writable?)"
        exit 1
    fi
}

install_files() {
    log "installing files to $OYG_DST"
    mkdir -p "$OYG_DST/lib" "$OYG_DST/modules" "$OYG_DST/etc" "$OYG_DST/backup" "$OYG_DST/watchers" "$OYG_DST/scripts"
    cp "$OYG_SRC/oyg" "$OYG_DST/oyg"
    cp "$OYG_SRC/lib/common.sh" "$OYG_DST/lib/common.sh"
    for f in "$OYG_SRC/modules"/*.sh; do
        [ -f "$f" ] || continue
        cp "$f" "$OYG_DST/modules/$(basename "$f")"
    done
    for f in "$OYG_SRC/etc"/*.txt; do
        [ -f "$f" ] || continue
        cp "$f" "$OYG_DST/etc/$(basename "$f")"
    done
    # scripts/ — operator tools that must be runnable from the device
    # (sniffer, DNS sinkhole resolver + wrapper + watchdog).
    for f in "$OYG_SRC"/scripts/*.sh "$OYG_SRC"/scripts/*.py; do
        [ -f "$f" ] || continue
        cp "$f" "$OYG_DST/scripts/$(basename "$f")"
    done
    chmod 0755 "$OYG_DST/oyg"
    chmod 0644 "$OYG_DST/lib/common.sh" 2>/dev/null || true
    for f in "$OYG_DST/etc"/*.txt; do
        [ -f "$f" ] || continue
        chmod 0644 "$f"
    done
    for f in "$OYG_DST/modules"/*.sh; do
        [ -f "$f" ] || continue
        chmod 0644 "$f"
    done
    for f in "$OYG_DST/scripts"/*.sh; do
        [ -f "$f" ] || continue
        chmod 0755 "$f"
    done
    for f in "$OYG_DST/scripts"/*.py; do
        [ -f "$f" ] || continue
        chmod 0755 "$f"
    done
}

install_watcher_templates() {
    log "writing watcher templates"
    cat >"$OYG_DST/watch-capture.sh" <<'EOF'
#!/bin/sh
# watch-capture.sh — re-tighten /tmp/capture.rgb every loop.
# Re-applies the mode because the OLED depletion writer re-creates the file.
while :; do
    if [ -e /tmp/capture.rgb ]; then
        chmod 000 /tmp/capture.rgb 2>/dev/null || chmod 0600 /tmp/capture.rgb 2>/dev/null
    fi
    sleep 3
done
EOF
    chmod 0755 "$OYG_DST/watch-capture.sh"

    cat >"$OYG_DST/watch-logs.sh" <<EOF
#!/bin/sh
# watch-logs.sh — periodic clear of plaintext logs.
# Interval: \${OYG_LOG_INTERVAL:-60}s
INTERVAL=\${OYG_LOG_INTERVAL:-60}
while :; do
    [ -e /tmp/var/log/messages ] && : >/tmp/var/log/messages 2>/dev/null
    [ -e /tmp/app.voice.log ]      && : >/tmp/app.voice.log      2>/dev/null
    sleep "\$INTERVAL"
done
EOF
    chmod 0755 "$OYG_DST/watch-logs.sh"
}

install_init_hook() {
    log "installing boot hook at $INIT_HOOK"
    if [ ! -d "$INITD" ]; then
        if ! mkdir -p "$INITD" 2>/dev/null; then
            warn "$INITD does not exist and cannot be created; skipping boot hook"
            warn "you will need to re-apply hardening manually after each reboot"
            return 0
        fi
    fi
    cat >"$INIT_HOOK" <<EOF
#!/bin/sh
# oyg boot hook — re-apply enabled hardening on every boot.
# Generated by own-your-glass/install.sh.
# Filename MUST NOT contain a dot — run-parts ignores dotfiles.
[ -x "$OYG_DST/oyg" ] || exit 0
BOOT_LOG=$OYG_DST/boot.log
STATE=$OYG_DST/state
STOPPED_LIST=$OYG_DST/services.stopped
KILL_LIST=$OYG_DST/services.kill
DEBLOAT_STOPPED_LIST=$OYG_DST/debloat.units.stopped
DEBLOAT_KILL_LIST=$OYG_DST/debloat.procs.kill
{
    date '+%Y-%m-%dT%H:%M:%S boot-hook start'
    # Wait briefly for the network to come up. The /etc/hosts bind-mount
    # and any ip-route work need a routable interface.
    waited=0
    while [ \$waited -lt 30 ]; do
        if ip route show default 2>/dev/null | grep -q '^default'; then
            break
        fi
        sleep 1
        waited=\$((waited + 1))
    done
    net_up=0
    if ip route show default 2>/dev/null | grep -q '^default'; then
        net_up=1
    else
        echo "[boot-hook] WARN: no default route after 30s — network-dependent modules will be skipped"
    fi

    # Re-apply capture (this re-establishes the bind-mount on
    # /usr/bin/vtCaptureTestSuite, which does NOT survive a reboot, and
    # re-tightens /tmp/capture.rgb via the watcher), mic (re-binds
    # /dev/null over every ALSA capture PCM node — also does NOT survive
    # a reboot), voice (re-binds /dev/null over the Magic Remote mic
    # pipeline binaries — also does NOT survive a reboot; /dev/hidraw0
    # is deliberately untouched because the mic button rides the same
    # HID channel as every other remote button), logs, remoteone,
    # apps (re-merges the curated blocklist — the application manager
    # may rewrite blockedSystemAppList/<REGION>.json on its own, so we
    # have to re-add our entries on every boot), and policy
    # (re-declines LG consents because the system silently re-accepts
    # them when related components update; re-touches the webOSbrew
    # update-blocker flag because touch is idempotent and the file does
    # not survive a firmware reset).
    $OYG_DST/oyg harden --only capture
    $OYG_DST/oyg harden --only mic
    $OYG_DST/oyg harden --only voice
    $OYG_DST/oyg harden --only logs
    $OYG_DST/oyg harden --only remoteone
    $OYG_DST/oyg harden --only apps
    $OYG_DST/oyg harden --only policy

    # Enforce previously-stopped services. systemctl mask is impossible
    # on this device (read-only /etc), so the model is "stop now + stop
    # on every boot". The harden run above re-populates the list, so we
    # read it here and re-stop each entry. Tolerant of services that are
    # already inactive (systemctl stop exits 0 in that case) and of a
    # missing file (nothing to enforce).
    if [ -r "\$STOPPED_LIST" ]; then
        while IFS= read -r svc; do
            [ -z "\$svc" ] && continue
            case "\$svc" in
                \#*) continue ;;
            esac
            if systemctl stop "\$svc" 2>/dev/null; then
                echo "[boot-hook] stopped: \$svc"
            else
                echo "[boot-hook] WARN: could not stop \$svc (already inactive?)"
            fi
        done <"\$STOPPED_LIST"
    fi

    # Kill previously-recorded process names. REQUIRED for luna-launched
    # services (e.g. iot-client) whose systemd unit is only a one-shot
    # wrapper that exits 0 immediately — systemctl stop is a no-op on
    # the running process. ls-hubd may respawn them on demand; this is
    # best-effort control, not a permanent disable. Tolerant of a missing
    # file (nothing to enforce) and of a process that isn't running.
    if [ -r "\$KILL_LIST" ]; then
        while IFS= read -r proc; do
            [ -z "\$proc" ] && continue
            case "\$proc" in
                \#*) continue ;;
            esac
            pids=\$(pidof "\$proc" 2>/dev/null) || pids=\$(pgrep -x -- "\$proc" 2>/dev/null) || pids=""
            if [ -z "\$pids" ]; then
                echo "[boot-hook] no such process: \$proc"
                continue
            fi
            for p in \$pids; do
                kill -TERM "\$p" 2>/dev/null && echo "[boot-hook] TERM \$proc (pid \$p)"
            done
            sleep 1
            survivors=\$(pidof "\$proc" 2>/dev/null) || survivors=\$(pgrep -x -- "\$proc" 2>/dev/null) || survivors=""
            for p in \$survivors; do
                kill -KILL "\$p" 2>/dev/null && echo "[boot-hook] KILL \$proc (pid \$p)"
            done
            remaining=\$(pidof "\$proc" 2>/dev/null) || remaining=\$(pgrep -x -- "\$proc" 2>/dev/null) || remaining=""
            if [ -n "\$remaining" ]; then
                echo "[boot-hook] WARN: \$proc still running after TERM+KILL (pid \$remaining)"
            fi
        done <"\$KILL_LIST"
    fi

    # Debloat re-apply: only when the user previously hardened the debloat
    # module (state has debloat.applied=1). Unlike the network module,
    # this does NOT depend on the network being up — debloat is purely
    # local process + bind-mount work. The debloat module's harden entry
    # point is gated on OYG_DEBLOAT=1; we re-export it from state so the
    # operator does not need to set it in the boot environment. We also
    # re-enforce the persisted debloat.units.stopped + debloat.procs.kill
    # lists using the same TERM/KILL pattern as services, so any process
    # that the system respawned since boot is killed again.
    if [ -r "\$STATE" ] && grep -q '^debloat.applied=1' "\$STATE"; then
        export OYG_DEBLOAT=1
        $OYG_DST/oyg harden --only debloat
    fi
    if [ -r "\$DEBLOAT_STOPPED_LIST" ]; then
        while IFS= read -r svc; do
            [ -z "\$svc" ] && continue
            case "\$svc" in
                \#*) continue ;;
            esac
            if systemctl stop "\$svc" 2>/dev/null; then
                echo "[boot-hook] debloat stop: \$svc"
            else
                echo "[boot-hook] WARN: debloat stop \$svc failed (already inactive?)"
            fi
        done <"\$DEBLOAT_STOPPED_LIST"
    fi
    if [ -r "\$DEBLOAT_KILL_LIST" ]; then
        while IFS= read -r proc; do
            [ -z "\$proc" ] && continue
            case "\$proc" in
                \#*) continue ;;
            esac
            pids=\$(pidof "\$proc" 2>/dev/null) || pids=\$(pgrep -x -- "\$proc" 2>/dev/null) || pids=""
            if [ -z "\$pids" ]; then
                echo "[boot-hook] debloat: no such process: \$proc"
                continue
            fi
            for p in \$pids; do
                kill -TERM "\$p" 2>/dev/null && echo "[boot-hook] debloat TERM \$proc (pid \$p)"
            done
            sleep 1
            survivors=\$(pidof "\$proc" 2>/dev/null) || survivors=\$(pgrep -x -- "\$proc" 2>/dev/null) || survivors=""
            for p in \$survivors; do
                kill -KILL "\$p" 2>/dev/null && echo "[boot-hook] debloat KILL \$proc (pid \$p)"
            done
            remaining=\$(pidof "\$proc" 2>/dev/null) || remaining=\$(pgrep -x -- "\$proc" 2>/dev/null) || remaining=""
            if [ -n "\$remaining" ]; then
                echo "[boot-hook] WARN: debloat \$proc still running after TERM+KILL (pid \$remaining)"
            fi
        done <"\$DEBLOAT_KILL_LIST"
    fi

    # Network re-apply: only when (a) the user previously hardened the
    # network module (state has network.applied=1), AND (b) the network is
    # up. We re-derive the opt-in flags from state so we don't need them in
    # the boot environment.
    if [ "\$net_up" = "1" ] && [ -r "\$STATE" ] \\
        && grep -q '^network.applied=1' "\$STATE"; then
        # The state file records which risky sub-flags the user enabled.
        # We export them so the network module's harden entry point will
        # accept the request at boot.
        export OYG_NETWORK_BLOCK=1
        if grep -q '^network.strict=1' "\$STATE"; then
            export OYG_NETWORK_STRICT=1
        fi
        if grep -q '^network.ipblock=1' "\$STATE"; then
            export OYG_NETWORK_IPBLOCK=1
        fi
        if grep -q '^network.dns_override=1' "\$STATE"; then
            export OYG_DNS_OVERRIDE=1
        fi
        if grep -q '^network.dns_resolver=1' "\$STATE"; then
            export OYG_DNS_RESOLVER=1
        fi
        $OYG_DST/oyg harden --only network
        # The network module's layer 4 (dns.sh start) is idempotent; it
        # also re-spawns the watchdog if not already running. We never
        # restart connmand — only SIGHUP the existing pid.
    fi

    # Perms re-apply: only when the user previously hardened the perms
    # module (state has perms.applied=1). perms is purely local — it
    # chmods vendor + webOSbrew code paths — so it does NOT depend on
    # the network being up. We re-export OYG_AGGRESSIVE=1 from state so
    # the perms module's harden entry point will accept the request at
    # boot (the module refuses without the flag because changing vendor
    # + webOSbrew paths is invasive). webOSbrew updates may re-extract
    # these paths in mode 0777 between boots, so the chmod needs to be
    # re-applied every boot — which is why this lives in the hook.
    # Operator flow: run 'OYG_AGGRESSIVE=1 oyg harden --only perms'
    # after install; that sets perms.applied=1 and the installer does
    # NOT run it for them.
    if [ -r "\$STATE" ] && grep -q '^perms.applied=1' "\$STATE"; then
        export OYG_AGGRESSIVE=1
        $OYG_DST/oyg harden --only perms
    fi
    date '+%Y-%m-%dT%H:%M:%S boot-hook done'
} >\$BOOT_LOG 2>&1
EOF
    chmod 0755 "$INIT_HOOK"
    log "boot hook installed at $INIT_HOOK (will re-apply capture/mic/voice/logs/remoteone/apps/policy, enforce services.stopped + services.kill, and state-gated: debloat, network, perms when previously applied)"
}

main() {
    require_root
    require_dst_writable
    install_files
    install_watcher_templates
    install_init_hook
    cat <<EOF

== install complete ==

Next steps on device:

  # 1. list available modules
  $OYG_DST/oyg list

  # 2. dry-run the safe modules
  $OYG_DST/oyg harden --dry-run

  # 3. apply the safe modules (services, capture, mic, logs, remoteone)
  #    NOTE: services uses 'stop + boot-enforce' (mask is impossible on
  #    this device because /etc is a read-only overlay).
  $OYG_DST/oyg harden

  # 4. opt-in risky modules
  OYG_AGGRESSIVE=1 $OYG_DST/oyg harden --only services
  OYG_AGGRESSIVE=1 $OYG_DST/oyg harden --only perms
  OYG_NETWORK_BLOCK=1 $OYG_DST/oyg harden --only network

  # 5. verify
  $OYG_DST/oyg verify

Boot hook: $INIT_HOOK
EOF
}

main "$@"
