#!/usr/bin/env python3
# dnssink.py — on-device DNS sinkhole resolver (pure Python stdlib).
#
# Listens on 127.0.0.2:53 (UDP + TCP) on a rooted LG webOS TV and answers
# queries for the blocklisted names with a sinkhole (0.0.0.0 for A, :: for
# AAAA, NXDOMAIN otherwise); everything else is forwarded to the upstream
# resolver discovered at start time and the response is relayed byte-for-
# byte (transaction ID preserved). Source of truth for the blocklist is
# /var/lib/own-your-glass/hosts (regenerated by `modules/network.sh` from
# etc/blocklist-{upstream-safe,oyg}.txt). mtime-watched, so re-running
# `oyg harden --only network` is picked up without a restart.
#
# Why on-device, why 127.0.0.2:53 (verified on OLED55B56LA / webOS 10.3.1):
#   - glibc `getent` honours /etc/hosts, but webOS daemons do NOT — they
#     hand the name directly to ConnMan's DNS proxy on 127.0.0.1:53, which
#     itself forwards upstream and ignores /etc/hosts. Verified:
#       getent hosts ngfts.nextlgsdp.com      -> ::1  (blocked by hosts)
#       nslookup ngfts.nextlgsdp.com 127.0.0.1 -> 23.211.135.15 (real IP)
#     The TV then *connected* to that IP. Hosts-file blocking is therefore
#     insufficient on this device. /etc/hosts also cannot express subdomains
#     one-by-one — blocking `nextlgsdp.com` did nothing for `es.nextlgsdp.com`.
#   - 127.0.0.2 is in the loopback /8 and is bindable (verified). The
#     sinkhole is wired in by `scripts/dns.sh`, which bind-mounts a
#     managed /etc/resolv.conf over the real one (127.0.0.2 first, the
#     DHCP-learned upstream as fallback). The PREVIOUS route — editing
#     connman's service settings and nudging connmand — took this TV off
#     the network for ~30 minutes and is banned: this toolkit NEVER
#     signals, reloads or restarts connmand (see the post-mortem in
#     scripts/dns.sh).
#
# Why pure stdlib (no dnslib / twisted / etc): matches the convention set by
# scripts/sniff.py (also pure stdlib) and means `python3 scripts/dnssink.py`
# is the only thing on the load path. Survives busybox-only PATH.
#
# Robustness: malformed packets are counted and dropped, never crashed on.
# TCP path is guarded by per-connection timeouts. SIGTERM cleanly closes
# both sockets, the listening thread joins, and the audit log is flushed.

import argparse
import os
import signal
import socket
import struct
import sys
import threading
import time

PROG = "dnssink"

DEFAULT_HOSTS = "/var/lib/own-your-glass/hosts"
DEFAULT_BIND = "127.0.0.2"
DEFAULT_PORT = 53
DEFAULT_LOG = "/var/lib/own-your-glass/dns-audit.log"
DEFAULT_UPSTREAM_TIMEOUT = 2.5
DEFAULT_TCP_IDLE_TIMEOUT = 5.0

QTYPE_A = 1
QTYPE_AAAA = 28

# Class IN only is interesting here. We still parse + relay other classes
# upstream — the user might be hitting us with a chaos class for diagnostics.
QCLASS_IN = 1


def ts():
    return time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime())


def ts_compact():
    return time.strftime("%H:%M:%S", time.localtime())


def log(line, fh=None):
    sys.stdout.write(line + "\n")
    sys.stdout.flush()
    if fh is not None:
        try:
            fh.write(line + "\n")
            fh.flush()
        except OSError:
            pass


class HostsRules:
    """Suffix-match blocklist loaded from /var/lib/own-your-glass/hosts.

    The hosts file is the single source of truth — generated by
    `modules/network.sh` from `etc/blocklist-*.txt`. Lines that look like:

        0.0.0.0 example.com
        ::1     es.example.com

    populate suffix rules. `localhost` is never matched (it appears in
    the hosts file as the baseline 127.0.0.1 line, and a /etc/hosts
    sinkhole of localhost would black-hole the box's loopback traffic).
    Stored as sets of (labels-tuple) for O(1) suffix checks against the
    parsed QNAME. mtime is checked before each scan; reload is automatic.
    """

    __slots__ = ("path", "mtime", "rules", "count")

    def __init__(self, path):
        self.path = path
        self.mtime = 0.0
        self.rules = set()
        self.count = 0
        self.reload()

    def reload(self):
        rules = set()
        try:
            with open(self.path, "rb") as fh:
                for raw in fh:
                    try:
                        line = raw.decode("ascii", errors="replace").strip()
                    except Exception:
                        continue
                    if not line:
                        continue
                    parts = line.split()
                    if len(parts) < 2:
                        continue
                    addr = parts[0]
                    if addr not in ("0.0.0.0", "::1"):
                        continue
                    name = parts[1].rstrip(".").lower()
                    if not name or name == "localhost" or name.endswith(".localhost"):
                        continue
                    rules.add(tuple(reversed(name.split("."))))
        except FileNotFoundError:
            self.mtime = 0.0
            self.rules = set()
            self.count = 0
            return
        except OSError as e:
            sys.stderr.write("%s: cannot read %s: %s\n" % (PROG, self.path, e))
            self.mtime = 0.0
            self.rules = set()
            self.count = 0
            return
        self.rules = rules
        self.count = len(rules)
        try:
            self.mtime = os.stat(self.path).st_mtime
        except OSError:
            self.mtime = 0.0

    def refresh_if_changed(self):
        try:
            mt = os.stat(self.path).st_mtime
        except FileNotFoundError:
            if self.mtime != 0.0 or self.rules:
                self.mtime = 0.0
                self.rules = set()
                self.count = 0
                return True
            return False
        except OSError:
            return False
        if mt != self.mtime:
            self.reload()
            return True
        return False

    def matches(self, qname):
        if not qname:
            return False
        labels = tuple(qname.rstrip(".").lower().split("."))
        if not labels or labels[-1] == "":
            return False
        if labels[-1] == "localhost":
            return False
        n = len(labels)
        for i in range(1, n + 1):
            rule = tuple(reversed(labels[n - i:]))
            if rule in self.rules:
                return True
        return False


def parse_name(payload, off):
    labels = []
    cur = off
    end = None
    jumped = False
    while cur < len(payload):
        ln = payload[cur]
        if ln == 0:
            cur += 1
            end = cur
            break
        if (ln & 0xC0) == 0xC0:
            if cur + 1 >= len(payload):
                return None, cur + 2
            ptr = ((ln & 0x3F) << 8) | payload[cur + 1]
            if ptr >= cur:
                return None, cur + 2
            if not jumped:
                end = cur + 2
                jumped = True
            cur = ptr
            continue
        if (ln & 0xC0) == 0x40:
            return None, cur + 1
        if cur + 1 + ln > len(payload):
            return None, len(payload)
        labels.append(payload[cur + 1:cur + 1 + ln].decode("ascii", errors="replace"))
        cur += 1 + ln
    if end is None:
        return None, cur
    name = ".".join(labels).rstrip(".")
    return name, end


def parse_query(payload):
    if len(payload) < 12:
        return None
    flags = struct.unpack_from(">H", payload, 2)[0]
    qdcount = struct.unpack_from(">H", payload, 4)[0]
    if qdcount < 1:
        return None
    if (flags >> 15) & 1:
        return None
    name, off = parse_name(payload, 12)
    if name is None:
        return None
    if off + 4 > len(payload):
        return None
    qtype, qclass = struct.unpack_from(">HH", payload, off)
    return name, qtype, qclass


def build_blocked_answer(qname, qtype, txn_id):
    if qtype == QTYPE_A:
        name_bytes = encode_name(qname)
        answer = (
            name_bytes + struct.pack(">HHIH", 1, 1, 30, 4) + b"\x00\x00\x00\x00"
        )
        header = struct.pack(
            ">HHHHHH",
            txn_id,
            0x8180,
            1, 1, 0, 0,
        )
        question = (
            name_bytes + struct.pack(">HH", qtype, QCLASS_IN)
        )
        return header + question + answer, True
    if qtype == QTYPE_AAAA:
        name_bytes = encode_name(qname)
        answer = (
            name_bytes + struct.pack(">HHIH", 28, 1, 30, 16) + (b"\x00" * 16)
        )
        header = struct.pack(
            ">HHHHHH",
            txn_id,
            0x8180,
            1, 1, 0, 0,
        )
        question = (
            name_bytes + struct.pack(">HH", qtype, QCLASS_IN)
        )
        return header + question + answer, True
    name_bytes = encode_name(qname)
    question = (
        name_bytes + struct.pack(">HH", qtype, QCLASS_IN)
    )
    header = struct.pack(
        ">HHHHHH",
        txn_id,
        0x8183,
        1, 0, 0, 0,
    )
    return header + question, False


def encode_name(qname):
    out = b""
    for label in qname.rstrip(".").split("."):
        b = label.encode("ascii", errors="replace")
        if len(b) > 63:
            b = b[:63]
        out += bytes([len(b)]) + b
    return out + b"\x00"


def _set_recv_timeout(sock, t):
    try:
        sock.settimeout(t)
    except OSError:
        pass


def forward_udp(upstream, payload, timeout, port=53):
    try:
        family = socket.AF_INET6 if ":" in upstream else socket.AF_INET
        s = socket.socket(family, socket.SOCK_DGRAM)
    except OSError:
        return None
    _set_recv_timeout(s, timeout)
    try:
        s.sendto(payload, (upstream, port))
        data, _ = s.recvfrom(4096)
        return data
    except (OSError, socket.timeout):
        return None
    finally:
        try:
            s.close()
        except OSError:
            pass


def forward_tcp(upstream, payload, timeout, port=53):
    try:
        family = socket.AF_INET6 if ":" in upstream else socket.AF_INET
        s = socket.socket(family, socket.SOCK_STREAM)
    except OSError:
        return None
    _set_recv_timeout(s, timeout)
    try:
        s.connect((upstream, port))
        s.sendall(struct.pack(">H", len(payload)) + payload)
        hdr = recv_exact(s, 2, timeout)
        if hdr is None or len(hdr) < 2:
            return None
        ln = struct.unpack(">H", hdr)[0]
        body = recv_exact(s, ln, timeout)
        if body is None:
            return None
        return body
    except (OSError, socket.timeout):
        return None
    finally:
        try:
            s.close()
        except OSError:
            pass


def recv_exact(sock, n, timeout):
    deadline = time.monotonic() + timeout
    out = b""
    while len(out) < n:
        remain = deadline - time.monotonic()
        if remain <= 0:
            return None
        try:
            sock.settimeout(remain)
            chunk = sock.recv(n - len(out))
        except socket.timeout:
            return None
        except OSError:
            return None
        if not chunk:
            return None
        out += chunk
    return out


def _retxn(payload, txn_id):
    """Rewrite the first two bytes of a DNS datagram to txn_id.

    Cached datagrams (and, rarely, upstream replies) carry a foreign
    transaction ID. Clients validate it and drop mismatches, so relayed and
    cached responses must carry the current query's ID.
    """
    try:
        if len(payload) >= 2 and struct.unpack_from(">H", payload, 0)[0] != txn_id:
            return struct.pack(">H", txn_id) + payload[2:]
    except struct.error:
        pass
    return payload


class Cache:
    __slots__ = ("max_entries", "ttl_seconds", "lock", "data")

    def __init__(self, max_entries, ttl_seconds):
        self.max_entries = max_entries
        self.ttl_seconds = ttl_seconds
        self.lock = threading.Lock()
        self.data = {}

    def get(self, key):
        if self.ttl_seconds <= 0 or self.max_entries <= 0:
            return None
        now = time.monotonic()
        with self.lock:
            entry = self.data.get(key)
            if entry is None:
                return None
            payload, expires, _ = entry
            if expires <= now:
                try:
                    del self.data[key]
                except KeyError:
                    pass
                return None
            return payload

    def put(self, key, payload):
        if self.ttl_seconds <= 0 or self.max_entries <= 0:
            return
        now = time.monotonic()
        with self.lock:
            if key in self.data:
                del self.data[key]
            elif len(self.data) >= self.max_entries:
                try:
                    del self.data[next(iter(self.data))]
                except (KeyError, StopIteration):
                    pass
            self.data[key] = (payload, now + self.ttl_seconds, now)


class Resolver:
    __slots__ = (
        "bind", "port", "upstream", "upstream_port", "upstream_timeout",
        "rules", "audit_fh", "cache",
        "udp_sock", "tcp_sock", "running", "counts",
        "lock", "tcp_clients",
    )

    def __init__(self, bind, port, upstream, timeout, rules, audit_fh, cache,
                 upstream_port=53):
        self.bind = bind
        self.port = port
        self.upstream = upstream
        self.upstream_port = upstream_port
        self.upstream_timeout = timeout
        self.rules = rules
        self.audit_fh = audit_fh
        self.cache = cache
        self.udp_sock = None
        self.tcp_sock = None
        self.running = True
        self.counts = {"q": 0, "block": 0, "forward": 0,
                       "cache_hit": 0, "fwd_fail": 0, "parse_skip": 0,
                       "tcp_conn": 0, "udp_pkts": 0, "tcp_pkts": 0}
        self.lock = threading.Lock()
        self.tcp_clients = []

    def log(self, line):
        log(line, self.audit_fh)

    def open_sockets(self):
        if ":" in self.bind:
            family = socket.AF_INET6
            sockaddr = (self.bind, self.port, 0, 0)
        else:
            family = socket.AF_INET
            sockaddr = (self.bind, self.port)
        for stype, name in ((socket.SOCK_DGRAM, "UDP"), (socket.SOCK_STREAM, "TCP")):
            try:
                s = socket.socket(family, stype)
            except OSError as e:
                sys.stderr.write("%s: cannot create %s socket: %s\n" % (PROG, name, e))
                return False
            try:
                if stype == socket.SOCK_STREAM:
                    try:
                        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                    except OSError:
                        pass
                s.bind(sockaddr)
            except OSError as e:
                sys.stderr.write("%s: bind(%s:%d %s) failed: %s\n" %
                                 (PROG, self.bind, self.port, name, e))
                try:
                    s.close()
                except OSError:
                    pass
                return False
            try:
                s.setsockopt(socket.IPPROTO_IP, socket.IP_TTL, 64)
            except (OSError, AttributeError):
                pass
            if stype == socket.SOCK_STREAM:
                try:
                    s.listen(5)
                except OSError as e:
                    sys.stderr.write("%s: listen failed: %s\n" % (PROG, e))
                    try:
                        s.close()
                    except OSError:
                        pass
                    return False
            if stype == socket.SOCK_DGRAM:
                self.udp_sock = s
            else:
                self.tcp_sock = s
        return True

    def stop(self):
        self.running = False
        try:
            if self.udp_sock is not None:
                self.udp_sock.close()
        except OSError:
            pass
        try:
            if self.tcp_sock is not None:
                self.tcp_sock.close()
        except OSError:
            pass
        with self.lock:
            for t in list(self.tcp_clients):
                try:
                    t.join(timeout=0.5)
                except Exception:
                    pass

    def handle(self, payload, client, proto):
        try:
            self.counts["q"] += 1
            if proto == "udp":
                self.counts["udp_pkts"] += 1
            else:
                self.counts["tcp_pkts"] += 1
            if len(payload) < 12:
                self.counts["parse_skip"] += 1
                return
            try:
                txn_id = struct.unpack_from(">H", payload, 0)[0]
            except struct.error:
                self.counts["parse_skip"] += 1
                return
            parsed = parse_query(payload)
            if parsed is None:
                self.counts["parse_skip"] += 1
                return
            qname, qtype, qclass = parsed
            self.rules.refresh_if_changed()
            cache_key = (qname.lower(), qtype) if qname else None
            if cache_key is not None:
                cached = self.cache.get(cache_key)
                if cached is not None:
                    # The cached datagram carries the transaction ID of the
                    # query that populated it. Clients (BusyBox nslookup,
                    # glibc) validate the ID and DROP a mismatch, so it must
                    # be rewritten to the current query's ID on every hit.
                    self.counts["cache_hit"] += 1
                    self.send(client, _retxn(cached, txn_id), proto)
                    return
            if self.rules.matches(qname):
                resp, had_answer = build_blocked_answer(qname, qtype, txn_id)
                if had_answer:
                    self.counts["block"] += 1
                self.log("%s  BLOCK  %s  %s  qtype=%d from=%s proto=%s" %
                         (ts(), qname or "<root>",
                          "0.0.0.0" if qtype == QTYPE_A else
                          ("::" if qtype == QTYPE_AAAA else "NXDOMAIN"),
                          qtype, self.client_addr(client, proto), proto))
                if cache_key is not None:
                    self.cache.put(cache_key, resp)
                self.send(client, resp, proto)
                return
            for attempt in (1, 2):
                if proto == "udp":
                    resp = forward_udp(self.upstream, payload, self.upstream_timeout,
                                       port=self.upstream_port)
                else:
                    resp = forward_tcp(self.upstream, payload, self.upstream_timeout,
                                       port=self.upstream_port)
                if resp is not None:
                    # Relay byte-for-byte, but with the CLIENT's transaction
                    # ID (an upstream that answered a matching ID is passed
                    # through unchanged; a mismatch is rewritten).
                    resp = _retxn(resp, txn_id)
                    self.counts["forward"] += 1
                    if cache_key is not None:
                        self.cache.put(cache_key, resp)
                    self.send(client, resp, proto)
                    return
            self.counts["fwd_fail"] += 1
            servfail = build_servfail(txn_id, qname or "", qtype or QTYPE_A)
            self.send(client, servfail, proto)
        except Exception as e:
            sys.stderr.write("%s: handler crash: %s\n" % (PROG, e))

    def send(self, client, payload, proto):
        try:
            if proto == "udp":
                sock, addr, _ = client
                sock.sendto(payload, addr)
            else:
                sock, _ = client
                sock.sendall(struct.pack(">H", len(payload)) + payload)
        except OSError:
            pass

    def client_addr(self, client, proto):
        try:
            if proto == "udp":
                _, addr, _ = client
                return addr[0] if addr else "?"
            else:
                _, addr = client
                return addr[0] if addr else "?"
        except Exception:
            return "?"

    def serve_udp(self):
        sock = self.udp_sock
        while self.running:
            try:
                try:
                    sock.settimeout(1.0)
                    data, addr = sock.recvfrom(4096)
                except socket.timeout:
                    continue
                except OSError:
                    return
                self.handle(data, (sock, addr, None), "udp")
            except Exception as e:
                sys.stderr.write("%s: udp loop crash: %s\n" % (PROG, e))
                return

    def serve_tcp(self):
        sock = self.tcp_sock
        while self.running:
            try:
                try:
                    sock.settimeout(1.0)
                    conn, addr = sock.accept()
                except socket.timeout:
                    continue
                except OSError:
                    return
                self.counts["tcp_conn"] += 1
                with self.lock:
                    t = threading.Thread(
                        target=self._serve_tcp_conn,
                        args=(conn, addr),
                        daemon=True,
                        name="dnssink-tcp-%s" % (addr[0],),
                    )
                    t.start()
                    self.tcp_clients.append(t)
            except Exception as e:
                sys.stderr.write("%s: tcp loop crash: %s\n" % (PROG, e))
                return

    def _serve_tcp_conn(self, conn, addr):
        try:
            try:
                conn.settimeout(DEFAULT_TCP_IDLE_TIMEOUT)
            except OSError:
                pass
            deadline = time.monotonic() + DEFAULT_TCP_IDLE_TIMEOUT
            while self.running:
                remain = deadline - time.monotonic()
                if remain <= 0:
                    return
                try:
                    conn.settimeout(remain)
                    hdr = recv_exact(conn, 2, remain)
                    if hdr is None:
                        return
                    ln = struct.unpack(">H", hdr)[0]
                    payload = recv_exact(conn, ln, remain)
                    if payload is None:
                        return
                except (OSError, socket.timeout):
                    return
                self.handle(payload, (conn, addr), "tcp")
        except Exception as e:
            sys.stderr.write("%s: tcp conn crash: %s\n" % (PROG, e))
        finally:
            try:
                conn.close()
            except OSError:
                pass


def build_servfail(txn_id, qname, qtype):
    name_bytes = encode_name(qname or "")
    question = name_bytes + struct.pack(">HH", qtype or QTYPE_A, QCLASS_IN)
    header = struct.pack(
        ">HHHHHH",
        txn_id, 0x8182, 1, 0, 0, 0,
    )
    return header + question


def parse_args():
    p = argparse.ArgumentParser(
        prog=PROG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="on-device DNS sinkhole for rooted LG webOS TVs",
    )
    p.add_argument("--bind", default=os.environ.get("OYG_DNS_BIND", DEFAULT_BIND),
                   help="listen address (default: 127.0.0.2; env: OYG_DNS_BIND)")
    p.add_argument("--port", type=int, default=int(os.environ.get("OYG_DNS_PORT", DEFAULT_PORT)),
                   help="listen port (default: 53; env: OYG_DNS_PORT)")
    p.add_argument("--upstream", default=os.environ.get("OYG_DNS_UPSTREAM", ""),
                   help="upstream resolver IP (required if discovery fails)")
    p.add_argument("--hosts", default=os.environ.get("OYG_HOSTS_FILE", DEFAULT_HOSTS),
                   help="path to the generated hosts file (default: /var/lib/own-your-glass/hosts)")
    p.add_argument("--audit", default=os.environ.get("OYG_DNS_AUDIT", DEFAULT_LOG),
                   help="audit log path (default: /var/lib/own-your-glass/dns-audit.log)")
    p.add_argument("--upstream-timeout", type=float, default=DEFAULT_UPSTREAM_TIMEOUT,
                   help="seconds to wait for the upstream per attempt (default: 2.5)")
    p.add_argument("--cache-size", type=int, default=512,
                   help="max cache entries (default: 512)")
    p.add_argument("--cache-ttl", type=int, default=120,
                   help="cache TTL in seconds (default: 120)")
    return p.parse_args()


def main():
    args = parse_args()

    audit_fh = None
    try:
        dirpath = os.path.dirname(args.audit)
        if dirpath and not os.path.isdir(dirpath):
            try:
                os.makedirs(dirpath, exist_ok=True)
            except OSError as e:
                sys.stderr.write("%s: cannot mkdir %s: %s\n" %
                                 (PROG, dirpath, e))
        audit_fh = open(args.audit, "a", encoding="ascii", errors="replace")
    except OSError as e:
        sys.stderr.write("%s: cannot open audit log %s: %s\n" % (PROG, args.audit, e))
        audit_fh = None

    upstream = args.upstream
    if not upstream:
        # dns.sh discovers the upstream (connmanctl -> LS2 getStatus ->
        # gateway) and passes it here; keep ONE implementation of that
        # logic, not two. Bare manual runs must pass --upstream.
        sys.stderr.write("%s: no --upstream given (dns.sh always supplies it; "
                         "manual runs: --upstream <ip>)\n" % (PROG,))
        sys.exit(2)
    else:
        sys.stdout.write("%s: upstream=%s (configured)\n" % (PROG, upstream))

    rules = HostsRules(args.hosts)
    cache = Cache(args.cache_size, args.cache_ttl)
    resolver = Resolver(args.bind, args.port, upstream,
                        args.upstream_timeout, rules, audit_fh, cache)

    if not resolver.open_sockets():
        sys.exit(1)

    sys.stdout.write("%s: listening on %s:%d (udp+tcp), rules=%d, audit=%s\n" %
                     (PROG, args.bind, args.port, rules.count,
                      args.audit if audit_fh else "<stdout-only>"))
    sys.stdout.flush()

    def stop(_signum, _frame):
        resolver.stop()
    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)

    udp_thread = threading.Thread(target=resolver.serve_udp, daemon=True,
                                  name="dnssink-udp")
    tcp_thread = threading.Thread(target=resolver.serve_tcp, daemon=True,
                                  name="dnssink-tcp")
    udp_thread.start()
    tcp_thread.start()

    try:
        while resolver.running:
            time.sleep(0.5)
    except KeyboardInterrupt:
        resolver.stop()
    finally:
        udp_thread.join(timeout=2.0)
        tcp_thread.join(timeout=2.0)

    parts = ["", "%s: shutting down — q=%d block=%d forward=%d cache_hit=%d "
             "fwd_fail=%d parse_skip=%d udp=%d tcp=%d tcp_conn=%d" %
             (PROG, resolver.counts["q"], resolver.counts["block"],
              resolver.counts["forward"], resolver.counts["cache_hit"],
              resolver.counts["fwd_fail"], resolver.counts["parse_skip"],
              resolver.counts["udp_pkts"], resolver.counts["tcp_pkts"],
              resolver.counts["tcp_conn"])]
    sys.stdout.write("\n".join(parts) + "\n")
    sys.stdout.flush()



if __name__ == "__main__":
    main()
